# coding: utf-8

"""
    agent/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agent.models.sort_sort_field import SortSortField

class TestSortSortField(unittest.TestCase):
    """SortSortField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortSortField(self):
        """Test SortSortField"""
        # inst = SortSortField()

if __name__ == '__main__':
    unittest.main()
