# coding: utf-8

"""
    agent/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agent.models.agent_list_agents_request import AgentListAgentsRequest

class TestAgentListAgentsRequest(unittest.TestCase):
    """AgentListAgentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentListAgentsRequest:
        """Test AgentListAgentsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentListAgentsRequest`
        """
        model = AgentListAgentsRequest()
        if include_optional:
            return AgentListAgentsRequest(
                page_token = '',
                sorts = [
                    agent.models.list_request_sort.ListRequestSort(
                        evaluation_order = 56, 
                        field = 'UNKNOWN', 
                        order = 'DESC', )
                    ],
                filters_mask = '',
                filters = agent.models.list_request_filters.ListRequestFilters(
                    email = [
                        ''
                        ], 
                    lastname = [
                        ''
                        ], 
                    code = [
                        ''
                        ], )
            )
        else:
            return AgentListAgentsRequest(
        )
        """

    def testAgentListAgentsRequest(self):
        """Test AgentListAgentsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
