# coding: utf-8

"""
    agent/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agent.api.agent_api import AgentApi


class TestAgentApi(unittest.TestCase):
    """AgentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentApi()

    def tearDown(self) -> None:
        pass

    def test_agent_create_agent(self) -> None:
        """Test case for agent_create_agent

        """
        pass

    def test_agent_get_agent(self) -> None:
        """Test case for agent_get_agent

        """
        pass

    def test_agent_list_agents(self) -> None:
        """Test case for agent_list_agents

        """
        pass

    def test_agent_update_agent(self) -> None:
        """Test case for agent_update_agent

        """
        pass


if __name__ == '__main__':
    unittest.main()
