# coding: utf-8

"""
    agent/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agent.models.agent_create_agent_request import AgentCreateAgentRequest

class TestAgentCreateAgentRequest(unittest.TestCase):
    """AgentCreateAgentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentCreateAgentRequest:
        """Test AgentCreateAgentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentCreateAgentRequest`
        """
        model = AgentCreateAgentRequest()
        if include_optional:
            return AgentCreateAgentRequest(
                code = '',
                firstname = '',
                lastname = '',
                email = '',
                password = '',
                phone = ''
            )
        else:
            return AgentCreateAgentRequest(
        )
        """

    def testAgentCreateAgentRequest(self):
        """Test AgentCreateAgentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
