# coding: utf-8

"""
    agent/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agent.models.agent_sort_order import AgentSortOrder

class TestAgentSortOrder(unittest.TestCase):
    """AgentSortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentSortOrder(self):
        """Test AgentSortOrder"""
        # inst = AgentSortOrder()

if __name__ == '__main__':
    unittest.main()
