# coding: utf-8

"""
    agent/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agent.models.list_request_sort import ListRequestSort

class TestListRequestSort(unittest.TestCase):
    """ListRequestSort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListRequestSort:
        """Test ListRequestSort
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListRequestSort`
        """
        model = ListRequestSort()
        if include_optional:
            return ListRequestSort(
                evaluation_order = 56,
                field = 'UNKNOWN',
                order = 'DESC'
            )
        else:
            return ListRequestSort(
        )
        """

    def testListRequestSort(self):
        """Test ListRequestSort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
